<a href="https://colab.research.google.com/github/ClauRozasG/An-lisis-crediticio/blob/main/Cr%C3%A9dito_en_tarjetas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROBLEMA DE NEGOCIO**

---------------------------------------------------------------

La importancia de reducir el riesgo crediticio ha llevado a una institución financiera alemana a buscar soluciones innovadoras. Como científicos de datos, hemos sido convocados para construir un modelo de machine learning preciso y confiable que sea capaz de evaluar con mayor precisión la probabilidad de incumplimiento crediticio de sus clientes.

Tus tareas principales serán:
1. Preprocesamiento de Datos: Realizar limpieza de datos, manejar valores faltantes, codificación de variables categóricas y normalización/escalado de datos.

2. Exploración de Datos: Analizar y comprender el conjunto de datos proporcionado, identificar variables llaves y realizar visualizaciones para entender las relaciones entre las variables y seleccionar las características relevantes.

3. Construcción de Modelos: Experimentar con algunos algoritmos de machine learning como Regresión Logística, Árboles de Decisión, Random Forest, Naive Bayes, entre otros.

4. Evaluación y Selección del Modelo: Evaluar los modelos utilizando métricas como precisión, recall, área bajo la curva ROC, y F1-score. Seleccionar el modelo con el mejor rendimiento para la predicción de la solvencia crediticia.

**Importamos las librerías**

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score, roc_curve
global df_banco, resultados

In [ ]:
global df_banco, resultados

In [ ]:
df_banco=pd.read_csv("german_credit.csv")
df_banco.head()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,other_debtors,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,none,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,none,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,guarantor,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,none,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [ ]:
df_banco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   default                     1000 non-null   int64
 1   account_check_status        1000 non-null   object
 2   duration_in_month           1000 non-null   int64
 3   credit_history              1000 non-null   object
 4   purpose                     1000 non-null   object
 5   credit_amount               1000 non-null   int64
 6   savings                     1000 non-null   object
 7   present_emp_since           1000 non-null   object
 8   installment_as_income_perc  1000 non-null   int64
 9   personal_status_sex         1000 non-null   object
 10  other_debtors               1000 non-null   object
 11  present_res_since           1000 non-null   int64
 12  property                    1000 non-null   object
 13  age                         1000 non-null   int64
 14  other_installment_plans     1000 non-null   object
 15  housing                     1000 non-null   object
 16  credits_this_bank           1000 non-null   int64
 17  job                         1000 non-null   object
 18  people_under_maintenance    1000 non-null   int64
 19  telephone                   1000 non-null   object
 20  foreign_worker              1000 non-null   object
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [ ]:
df_banco.columns

Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

In [ ]:
print(df_banco.account_check_status.unique())
print(" ")
print(df_banco.credit_history.unique())
print(" ")
print(df_banco.purpose.unique())
print(" ")
print(df_banco.savings.unique())
print(" ")
print(df_banco.present_emp_since.unique())
print(" ")
print(df_banco.personal_status_sex.unique())
print(" ")
print(df_banco.other_debtors.unique())
print(" ")
print(df_banco.property.unique())
print(" ")
print(df_banco.other_installment_plans.unique())
print(" ")
print(df_banco.housing.unique())
print(" ")
print(df_banco.job.unique())
print(" ")
print(df_banco.telephone.unique())
print(" ")
print(df_banco.foreign_worker.unique())
print(" ")

#print(" ")

['< 0 DM' '0 <= ... < 200 DM' 'no checking account'
 '>= 200 DM / salary assignments for at least 1 year']

['critical account/ other credits existing (not at this bank)'
 'existing credits paid back duly till now'
 'delay in paying off in the past'
 'no credits taken/ all credits paid back duly'
 'all credits at this bank paid back duly']

['domestic appliances' '(vacation - does not exist?)' 'radio/television'
 'car (new)' 'car (used)' 'business' 'repairs' 'education'
 'furniture/equipment' 'retraining']

['unknown/ no savings account' '... < 100 DM' '500 <= ... < 1000 DM '
 '.. >= 1000 DM ' '100 <= ... < 500 DM']

['.. >= 7 years' '1 <= ... < 4 years' '4 <= ... < 7 years' 'unemployed'
 '... < 1 year ']

['male : single' 'female : divorced/separated/married'
 'male : divorced/separated' 'male : married/widowed']

['none' 'guarantor' 'co-applicant']

['real estate'
 'if not A121 : building society savings agreement/ life insurance'
 'unknown / no property'
 'if not A121/A122 : car or other, not in attribute 6']

['none' 'bank' 'stores']

['own' 'for free' 'rent']

['skilled employee / official' 'unskilled - resident'
 'management/ self-employed/ highly qualified employee/ officer'
 'unemployed/ unskilled - non-resident']

['yes, registered under the customers name ' 'none']

['yes' 'no']

In [ ]:
def duration_in_month(value):
  if 1<= value <12: return 1
  elif 12 <= value <24: return 2
  elif

In [ ]:
account_check_status = {'< 0 DM': 1,  '0 <= ... < 200 DM':2,  'no checking account':4,
 '>= 200 DM / salary assignments for at least 1 year':3}

credit_history ={'critical account/ other credits existing (not at this bank)':5,
 'existing credits paid back duly till now': 3,
 'delay in paying off in the past': 4,
 'no credits taken/ all credits paid back duly': 1,
 'all credits at this bank paid back duly': 2}

purpose= {'domestic appliances': 5, '(vacation - does not exist?)': 8, 'radio/television':4 ,
 'car (new)': 1, 'car (used)':2 ,'business':10 , 'repairs':6 , 'education':7 ,
 'furniture/equipment': 3, 'retraining':9}

savings = {'unknown/ no savings account':5, '... < 100 DM':1, '500 <= ... < 1000 DM ':3,
 '.. >= 1000 DM ':4, '100 <= ... < 500 DM':2}

present_emp_since= {'.. >= 7 years': 1, '1 <= ... < 4 years': 3, '4 <= ... < 7 years' :4 ,'unemployed':5 ,
 '... < 1 year ':4 }

personal_status_sex = {'male : single':3 , 'female : divorced/separated/married':2 ,
 'male : divorced/separated':1 , 'male : married/widowed':4 }

other_debtors={'none':1 , 'guarantor': 3, 'co-applicant':2}

property ={'real estate': 1,
 'if not A121 : building society savings agreement/ life insurance': 2,
 'unknown / no property':4,
 'if not A121/A122 : car or other, not in attribute 6':3}

other_installment_plans={'none': 3, 'bank' : 1,'stores':2}

housing={'own': 2, 'for free': 3, 'rent':1}

job={'skilled employee / official':3 , 'unskilled - resident': 2,
 'management/ self-employed/ highly qualified employee/ officer': 4,
 'unemployed/ unskilled - non-resident': 1}

telephone={'yes, registered under the customers name ': 1, 'none': 0}

foreign_worker={'yes': 1 , 'no': 0}

In [ ]:
def procesar_datos():
  global df_banco, resultados
  df_banco.drop_duplicates()